
const actionTypes = {
    UPDATE_TOKENS_SUCCESS: 'UPDATE_TOKENS_SUCCESS',
    UPDATE_TOKENS_FAILD: 'UPDATE_TOKENS_FAILD',
    GET_LOGIN_START: 'GET_LOGIN_START',
    GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
    GET_LOGIN_FAILD: 'GET_LOGIN_FAILD',
    USER_LOGOUT: 'USER_LOGOUT',
    UPDATE_LIST_CART: 'UPDATE_LIST_CART',
    UPDATE_REDIRECT_LOGIN: 'UPDATE_REDIRECT_LOGIN',

    UPDATE_LIST_KEYWORD: 'UPDATE_LIST_KEYWORD',
    SET_SHOW_SUGGESS_VIDEO: 'SET_SHOW_SUGGESS_VIDEO'
}

export default actionTypes;